name: Run Python
on:
    push:
    schedule:
    - cron: 00***
jobs:
    build:
        name: run py1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Python
          run: |
            python3 test.py # test